# Generated by Django 4.0.3 on 2022-08-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixedDisplacementAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentageDisplacementAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximumDisplacementAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(1, 'DISCOUNT'), (2, 'MARKUP')], max_length=1)),
                ('conditions', models.CharField(choices=[(1, 'B2B'), (2, 'B2C')], max_length=1)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st.action')),
            ],
        ),
    ]
