# Generated by Django 4.0.3 on 2022-08-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_rename_conditions_rule_usertypecondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='userTypeCondition',
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('1', 'DISCOUNT'), ('2', 'MARKUP')], max_length=1),
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTypeCondition', models.CharField(choices=[('1', 'B2B'), ('2', 'B2C')], max_length=1)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='st.rule')),
            ],
        ),
    ]
